### ISSUE TITLE
add a delay config like linger.ms in kafka producer

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-flink-connector#29]
refer to https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_linger.ms

default: 0, no delay.
if has value, although the record is not reach batch size, send them immediately.

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-flink-connector/pull/33 resolved it.
