### ISSUE TITLE
Add Support for Flink 1.13

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-flink-connector#38]
The maintainer doesn't have the bandwidth for this now, hopefully, anyone could help/volunteer on this.

**Comment by JimWen** [comment]
please check this pr
Add Support up to Flink 1.14
https://github.com/vesoft-inc/nebula-flink-connector/pull/52

**Comment by markjoin123** [comment]
May I ask when will you merge spending flink 1.14 version?

**Comment by spike-liu** [comment]
@wey-gu another implementation has been included in https://github.com/vesoft-inc/nebula-flink-connector/pull/57. Please feel free to review.

**Comment by wey-gu** [comment]
> @wey-gu another implementation has been included in #57. Please feel free to review.

Amazing, this is extra awesome! Thanks!!

**Comment by spike-liu** [comment]
> > @wey-gu another implementation has been included in #57. Please feel free to review.
> 
> Amazing, this is extra awesome! Thanks!!

It is our pleasure, Wey.

Currently we are working on a project which using flink SQL to process data like Kafka -> join nebula -> write nebula. We would like to contribute more codes to community in the future. Hence any comments are appreciated:)

**Comment by wey-gu** [comment]
Thank you so much @spike-liu !

It's so lucky to have you in the community, and if you don't mind, it's more than welcome to share your work in our meetup/blog, too :)

cc @tian-zhong @lisahui @Nicole00

**Comment by spike-liu** [comment]
> Thank you so much @spike-liu !
> 
> It's so lucky to have you in the community, and if you don't mind, it's more than welcome to share your work in our meetup/blog, too :)
> 
> cc @tian-zhong @lisahui @Nicole00

Definitely, best practice would also be scheduled in community.

**Comment by liuxiaocs7** [comment]
I noticed that Flink has updated the source and sink function interfaces, just as [FLIP-27: Refactor Source Interface](https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface) and [FLIP-143: Unified Sink API](https://cwiki.apache.org/confluence/display/FLINK/FLIP-143%3A+Unified+Sink+API), should we update the interfaces if we want to support more higher version of flink.

**Comment by Nicole00** [comment]
> I noticed that Flink has updated the source and sink function interfaces, just as [FLIP-27: Refactor Source Interface](https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface) and [FLIP-143: Unified Sink API](https://cwiki.apache.org/confluence/display/FLINK/FLIP-143%3A+Unified+Sink+API), should we update the interfaces if we want to support more higher version of flink.

Great idea! @spike-liu could you take up your precious time to discuss this idea together if you are interested in it? We'll be very glad to hear from you and your team.

**Comment by spike-liu** [comment]
> > I noticed that Flink has updated the source and sink function interfaces, just as [FLIP-27: Refactor Source Interface](https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface) and [FLIP-143: Unified Sink API](https://cwiki.apache.org/confluence/display/FLINK/FLIP-143%3A+Unified+Sink+API), should we update the interfaces if we want to support more higher version of flink.
> 
> Great idea! @spike-liu could you take up your precious time to discuss this idea together if you are interested in it? We'll be very glad to hear from you and your team.

This is our honor, @Nicole00. 

There are a lot of information in these two proposals. Please give us some time to read them.

@liuxiaocs7 Thanks for bring it on.

**Comment by spike-liu** [comment]
@wey-gu this issue could be closed and completed in https://github.com/vesoft-inc/nebula-flink-connector/commit/93df7a1c1eec0219fcfb8947959b46595c92b6b1

**Comment by wey-gu** [comment]
Roger that :) Thanks a lot, @spike-liu !

Thanks a lot for @liuxiaocs7 and @JimWen , too!

**Comment by spike-liu** [comment]
> Roger that :) Thanks a lot, @spike-liu !
> 
> Thanks a lot for @liuxiaocs7 and @JimWen , too!

My pleasure, Wey.
