### ISSUE TITLE
Will nebula-flink-connector support flink sql?

### ISSUE THREAD

**Issue by neeuq** [vesoft-inc/nebula-flink-connector#4]
现在使用flink sql能更快速的支持业务开发，后续是否会提供支持

**Comment by Nicole00** [comment]
flink sql的需求可以加入考虑，也欢迎你贡献sql的功能~

**Comment by spike-liu** [comment]
@Nicole00 an implementation has been included in https://github.com/vesoft-inc/nebula-flink-connector/pull/57. Please feel free to review.

**Comment by Nicole00** [comment]
> @Nicole00 an implementation has been included in #57. Please feel free to review.

Thanks for your contribution, on the way~

**Comment by spike-liu** [comment]
> > @Nicole00 an implementation has been included in #57. Please feel free to review.
> 
> Thanks for your contribution, on the way~

My pleasure, Nicole.

**Comment by Nicole00** [comment]
#57 and https://github.com/vesoft-inc/nebula-flink-connector/pull/60 resolved it.
