### ISSUE TITLE
NebulaBatchOutputFormat.commit is not return when source data amount is small

### ISSUE THREAD

**Issue by ystaticy** [vesoft-inc/nebula-flink-connector#5]
In NebulaBatchOutputFormat.commit
there is :
```
numPendingRow.compareAndSet(executionOptions.getBatch(), 0);
```

when we set executionOptions.setBatch = 100;
But we only have 50 rows in DataSource;

numPendingRow(  =50) will not euqals executionOptions.getBatch()( =100); 
numPendingRow will not reset to 0;

the flush() while loop will running all the time;it will block the flink checkpoint 

so I think we should change the first parameter of numPendingRow.compareAndSet

it should be:
```
long pendingRow=numPendingRow.get();
numPendingRow.compareAndSet(pendingRow ,0);
```

**Comment by Nicole00** [comment]
Sorry for reply late. This is a bug for `flush`, the update for numPendingRow should be changed.
Can you please push a pr to fix this?

**Comment by ystaticy** [comment]
> Sorry for reply late. This is a bug for `flush`, the update for numPendingRow should be changed.
> Can you please push a pr to fix this?

Thanks for your reply.
I will push a pr to fix it.

**Comment by ystaticy** [comment]
> Sorry for reply late. This is a bug for `flush`, the update for numPendingRow should be changed.
> Can you please push a pr to fix this?

I already push a pr : https://github.com/vesoft-inc/nebula-flink-connector/pull/6
can you help me to review it?

**Comment by Nicole00** [comment]
Thank you for your contribution! Please sign our Contributor License Agreement as mentioned in your PR.
