### ISSUE TITLE
Local UT would fail caused by IP used by Nebula JAVA client is not accessible

### ISSUE THREAD

**Issue by spike-liu** [vesoft-inc/nebula-flink-connector#59]
- Nebula Java Client would get storage server IP which is defined in docker network environment.
- Local development is isolated from docker network environment.

Read data from Flink would fail in UT. The only way I can figure out is running UT in the same docker network environment. However it would cause debug codes impossible.

@Nicole00 Would you please enlighten us here?

**Comment by liuxiaocs7** [comment]
The [disscussion](https://discuss.nebula-graph.com.cn/) will helps.

**Comment by spike-liu** [comment]
> The [disscussion](https://discuss.nebula-graph.com.cn/) will help.

Thanks, Liu.

**Comment by wey-gu** [comment]
I understand that you would like to leverage your local desktop's IDE on debugging things, while the current design required a docker spawned nebula cluster to actually run java client in same docker network with nebula cluster.

The hack way would be(as java storage client get list of storaged from meta, that is domain name like `storaged0`) we could optionally do ssh port forwarding + dns hosts to make storaged0 being resolved to the remote server's storaged docker instance(with 9779 being exposed, too)... which is not actually practical.

I would suggest instead deploying a cluster without docker for now with the host configured as an externally accessible address.

**Comment by spike-liu** [comment]
> I understand that you would like to leverage your local desktop's IDE on debugging things, while the current design required a docker spawned nebula cluster to actually run java client in same docker network with nebula cluster.
> 
> The hack way would be(as java storage client get list of storaged from meta, that is domain name like `storaged0`) we could optionally do ssh port forwarding + dns hosts to make storaged0 being resolved to the remote server's storaged docker instance(with 9779 being exposed, too)... which is not actually practical.
> 
> I would suggest instead deploying a cluster without docker for now with the host configured as an externally accessible address.

Thank you so much. You really save my day! 

Only god knows how many efforts I have tried already. Such as updating ip during debug, running UT in docker, etc...however no luck so far.

I would try your solution.
