### ISSUE TITLE
Do we need to support FLIP-27: Refactor Source Interface

### ISSUE THREAD

**Issue by spike-liu** [vesoft-inc/nebula-flink-connector#65]
Split discussion from https://github.com/vesoft-inc/nebula-flink-connector/issues/38

**Comment by spike-liu** [comment]
https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface

**Comment by spike-liu** [comment]
Here is my research:

1. The problems mentioned below current are not problem for nebula connector.
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/9884987/179142456-b625cc5e-3996-4a32-b433-0384191755bc.png">

2. Currently only message queue framework, such as Kafka/Pulsar, implemented this new API.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/9884987/179142590-629f70bc-4a38-496a-8a06-45dff5dfa64f.png">


So far, from my point of view, there is no motivation for us to implement these new source API.

**Comment by Nicole00** [comment]
Sorry I missed this issue, I'll research it and reply later.

**Comment by Nicole00** [comment]
I agree with @spike-liu .
The main motivation of flip-27 is to facilitate the expansion of data sources and lower the threshold for everyone to contribute source code. Sense we have extended the Nebula data source, it seems there's no need to refactor the interface. 

And the use requirement of checkpoint is not high, so I tend to see the support of FILP-27 as a future requirement.

**Comment by spike-liu** [comment]
Thanks for your reply. @Nicole00 

Closed.
