### ISSUE TITLE
flink现在能否支持nebula-java2.0.0

### ISSUE THREAD

**Issue by 0xqq** [vesoft-inc/nebula-flink-connector#7]
flink现在能否支持nebula-java2.0.0

**Comment by Nicole00** [comment]
flink支持nebula 2.0的， 所用的client版本更改为2.0.0，然后根据readme编译就好。

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-flink-connector/pull/8 这个PR已经更新了 nebula-client 的版本，你可以拉下新的代码直接编译flink-connector。
