### ISSUE TITLE
Session not existed!

### ISSUE THREAD

**Issue by zjtaozjtw** [vesoft-inc/nebula-flink-connector#83]
session 过期后没有自动重新获取session，导致sink失败，希望支持自动获取正常session的逻辑。

**Comment by Nicole00** [comment]
> session 过期后没有自动重新获取session，导致sink失败，希望支持自动获取正常session的逻辑。

感谢反馈，你可以详细描述下你的现象吗，是启动后长时间没有数据生成，然后再次有新数据时sink失败，提示session not existed？

**Comment by zjtaozjtw** [comment]
> > session 过期后没有自动重新获取session，导致sink失败，希望支持自动获取正常session的逻辑。
> 
> 感谢反馈，你可以详细描述下你的现象吗，是启动后长时间没有数据生成，然后再次有新数据时sink失败，提示session not existed？

对，session过期后没有自动获取session，现在默认不是8个小时吗，8个小时没数据session过期就入不了图了，要是能像go的sdk一样支持自动重连，并获取新的session就好了

**Comment by linhr** [comment]
@Nicole00 I've been working on some improvements on the error handling logic of the connector, and I've taken care of this issue. I'll share my PR when it's in good shape!

**Comment by wey-gu** [comment]
> 

Amazing, thanks so much @linhr , looking forward to your PR and please take your time :D

**Comment by Nicole00** [comment]
Looking forward to your pr @linhr, please feel free to contact with us if you have any issues, Thanks.
