### ISSUE TITLE
any plans to upgrade the version of Flink?

### ISSUE THREAD

**Issue by zqsgithub2023** [vesoft-inc/nebula-flink-connector#84]
**General Question**

**Comment by Nicole00** [comment]
> **General Question**

can you please describe your requirement for flink version?

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
