### ISSUE TITLE
Support UPSERT mode for sink

### ISSUE THREAD

**Issue by Sixkd** [vesoft-inc/nebula-flink-connector#89]
**Is your feature request related to a problem? Please describe.**
The current sink cannot support upsert function. When kafka data is repeated, insert mode will report an error due to vid repetition
**Describe the solution you'd like**

Expect to add vertex when vid does not exist, update the corresponding vertex information when vid already exists, and the same is true for edge

**Comment by wey-gu** [comment]
Are you interested in implementing the upsert mode?

Also one comment: upsert is relatively expensive, thus it's actually better to update and capture vid/edge not existing to call insert/upsert rather than perform upsert for all sinks, @Nicole00 please correct me if wrong.

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
